blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/Saasysoft/no-look-pass-sessions/discussions
    about: Ask questions or discuss ideas in Discussions
