name: Contribution Type
description: What type of contribution is this?
labels: []
body:
  - type: dropdown
    id: contribution-type
    attributes:
      label: Contribution type
      options:
        - skill
        - command
        - documentation
        - bug fix
        - other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the contribution
    validations:
      required: true
